<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfCombine extends BasesfCombine
{
  public function getFiles()
  {
    $data = parent::getData();
    $files = unserialize(base64_decode($data['files']));
    if (!is_array($files))
    {
      $files = array();
    }
    
    return $files;
  }
}